from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from uuid import UUID

from .schemas import RunResponse


def _runs_dir() -> Path:
    base = Path(__file__).resolve().parent / "data" / "runs"
    base.mkdir(parents=True, exist_ok=True)
    return base


def _run_path(run_id: str) -> Path:
    # Run ids are UUIDs generated by the server. Validating them here prevents
    # future callers of load_run from turning the id into a filesystem path.
    normalized = str(UUID(run_id))
    return _runs_dir() / f"{normalized}.json"


def save_run(run: RunResponse) -> Path:
    path = _run_path(run.run_id)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(run.model_dump(), handle, ensure_ascii=False, indent=2)
    return path


def load_run(run_id: str) -> dict[str, Any] | None:
    try:
        path = _run_path(run_id)
    except (ValueError, AttributeError):
        return None
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)
